const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.resolve('app/src/main/assets/ui');
const botCommandCatalogue=JSON.parse(require('child_process').execFileSync('python3',['-c',"import json,sys;sys.path.insert(0,'backend');import bot_socials;print(json.dumps({p:bot_socials.catalogue(p) for p in ('custom','traditional','takp')}))"],{encoding:'utf8'}));
const server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!/^[\w.-]+$/.test(name)){res.writeHead(404);res.end();return;}try{res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,name)));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
 let page;try{
  page=await browser.newPage({viewport:{width:1280,height:720}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript((botCommands)=>{
   window.fixture={profile:localStorage.profile||'custom',alive:localStorage.alive!=='false',client:false,running:false,jobs:[],calls:[],creation:localStorage.creation==='true',identityVersion:1,storageNeeded:false,storageStage:0,failStorage:false,revision:1,rosters:{42:[{id:8,name:'Savedbot',race:1,class:1,gender:0}],43:[]},receipts:{},failGenerate:false,failInstall:false,ambiguous:false,backups:[]};
   const identity=()=>fixture.profile+'-deployment-v'+fixture.identityVersion;
   const characters=()=>[{id:42,account_id:3,account:'Touchscreen',name:'Ownerchar',level:35},{id:43,account_id:4,account:'AnotherAccount',name:'Otherchar',level:8}];
   const creation=()=>({available:fixture.creation&&!fixture.running&&!fixture.client&&!fixture.storageNeeded,reason:fixture.running||fixture.client?'Stop the server and client before changing bots or socials':fixture.storageNeeded?'Offline creation requires transactional bot storage.':fixture.creation?'Ready':'Build and deploy this world’s bot creation utility.'});
   const status=()=>({profile:fixture.profile,identity:identity(),available:true,reason:'Ready',creation:creation(),races:[{id:1,name:'Human',classes:[{id:1,name:'Warrior'},{id:13,name:'Magician'}]},{id:128,name:'Iksar',classes:[{id:11,name:'Necromancer'}]}],genders:[{id:0,name:'Male'},{id:1,name:'Female'}],limits:{social_selection:20},social_commands:botCommands[fixture.profile],storage:{needed:fixture.profile!=='takp'&&fixture.storageNeeded,available:fixture.profile!=='takp',reason:fixture.storageNeeded?'Review storage before enabling bot creation.':'Ready',tables:fixture.storageNeeded?[{name:'character_data',from:'MyISAM',to:'InnoDB'},{name:'bot_data',from:'MyISAM',to:'InnoDB'}]:[]}});
   const commandSocials=(args,owner)=>{
    const result=[];for(const action of args.actions){const width=action==='spawn_group'?1:5;
     for(let start=0;start<args.bot_ids.length;start+=width){const ids=args.bot_ids.slice(start,start+width),names=ids.map(id=>fixture.rosters[args.owner_id].find(b=>b.id===id).name),modern=fixture.profile!=='takp',caption=botCommands[fixture.profile].find(c=>c.id===action).label;
      const templates=modern?{spawn:'botspawn ',follow:'follow reset byname ',report:'botreport byname ',stay:'guard byname ',taunt_off:'taunt off byname '}:{spawn:'spawn ',revive:'revive ',follow:'follow ',dps_off:'dps cast off '};
      const lines=action==='spawn_group'?['/pause 20, /say ^botspawn '+names[0],'/target '+owner.name,'/pause 5, /target '+names[0],'/invite']:names.map(name=>'/say '+(modern?'^':'#bot ')+templates[action]+name),index=result.length;
      result.push({social_id:action+'.'+String(action==='spawn_group'?ids[0]:index).padStart(24,'0'),action,bot_ids:ids,names,label:action==='spawn_group'?names[0]:caption+(args.bot_ids.length>width?' '+(start/width+1):''),page:2+Math.floor(index/12),button:index%12+1,lines});
     }
    }return result;
   };
   const state=()=>({profile:fixture.profile,running:fixture.running,settings:{ip:'127.0.0.1',login_port:5999,repo:'https://github.com/Russianranger/Server',ref:'main',workers:3,jobs:1},processes:{},jobs:fixture.jobs,source:{commit:'abc'},maps_ready:true,database_imported:true,build_ready:true,binaries_ready:true,client:{imported:true},traditional:{components:{},build:{},deployment:{}},takp:{components:{},build:{},deployment:{}},free_bytes:50e9});
   window.Trasc={call(id,op,input){setTimeout(()=>{const f=fixture,a=JSON.parse(input);f.calls.push({op,a});try{
    if(op!=='native_state'&&a.__profile&&a.__profile!==f.profile)throw Error('World profile changed');
    let result={};
    if(op==='native_state')result={profile:f.profile,installed:true,alive:f.alive,status:'Runtime ready',free_bytes:50e9};
    else if(op==='client_native_state')result={profile:f.profile,installed:true,alive:f.client,busy:false,status:'Stopped',launch_options:{}};
    else if(op==='state')result=state();
    else if(op==='profile_switch'){if(f.alive||f.client)throw Error('Stop runtime and client');f.profile=a.profile;localStorage.profile=a.profile;result={profile:a.profile};}
    else if(op==='runtime_start'){f.alive=true;localStorage.alive='true';}
    else if(op==='runtime_stop'){f.alive=false;localStorage.alive='false';}
    else if(op==='controller_state')result={sources:[],actions:[],layers:[{name:'Main',bindings:{}}],deadzone:.2,sensitivity:700};
    else if(op==='controller_capture')result={};
    else if(op==='files'||op==='native_files')result={path:'.',items:[],total:0,offset:0,next_offset:null};
    else if(op==='logs')result={text:'Bots fixture',names:['control.log']};
    else if(op==='log_retention')result={count:5};
    else if(op==='bots_status')result=status();
    else if(op==='bots_characters'){if(a.identity!==identity())throw Error('Stale identity');const q=a.query.toLowerCase();result={identity:identity(),characters:characters().filter(c=>[c.name,c.account].join(' ').toLowerCase().includes(q)),query:a.query};}
    else if(op==='bots_roster'){if(a.identity!==identity())throw Error('Stale identity');result={identity:identity(),owner:characters().find(c=>c.id===a.owner_id),bots:f.rosters[a.owner_id],creation:creation()};}
    else{
     let value={},error=null;
     if(op.startsWith('bots_')){
      if(a.identity!==identity())throw Error('Stale identity');if(f.running||f.client)throw Error('Stop server and client');const owner=characters().find(c=>c.id===a.owner_id);if(!owner&&!op.startsWith('bots_storage_'))throw Error('Missing owner');
      if(op==='bots_storage_preview')value={identity:identity(),preview_hash:'storage-'+f.storageStage,changes:f.storageStage===0?[{table:'character_data',from:'MyISAM',to:'InnoDB'},{table:'bot_data',from:'MyISAM',to:'InnoDB'}]:[{table:'bot_data',from:'MyISAM',to:'InnoDB'}],message:'Review the tables. A complete database backup is made before enabling.',backup_required:true};
      if(op==='bots_storage_enable'){if(a.preview_hash!=='storage-'+f.storageStage)throw Error('Stale storage preview');f.identityVersion++;if(f.failStorage){f.failStorage=false;f.storageStage=1;value={identity:identity(),complete:false,backup:'backups/storage-2.sql.gz',converted:['character_data'],remaining:[{name:'bot_data',from:'MyISAM',to:'InnoDB'}],error:'Second table could not be converted.',message:'Some tables enabled; review remaining storage.'};}else{f.storageStage=2;f.storageNeeded=false;value={identity:identity(),complete:true,backup:'backups/storage-3.sql.gz',converted:['bot_data'],remaining:[],message:'Bot storage enabled. Choose a character to continue.'};}}

      if(op==='bots_preview')value={identity:identity(),owner,bots:a.drafts.map(b=>({...b,name:b.name[0].toUpperCase()+b.name.slice(1).toLowerCase()})),preview_hash:'review-'+a.request_id,request_id:a.request_id,message:'Validated names and combinations.'};
      if(op==='bots_generate'){
       if(f.failGenerate){f.failGenerate=false;error='Generation did not commit. Retry the reviewed batch.';}
       else if(f.receipts[a.request_id])value={...f.receipts[a.request_id],idempotent:true};
       else{const bots=a.drafts.map((b,i)=>({...b,id:100+f.rosters[a.owner_id].length+i}));f.rosters[a.owner_id].push(...bots);value={identity:identity(),owner,bots,message:'Companions saved. Prepare their buttons.',idempotent:false};f.receipts[a.request_id]=value;}
      }
      if(op==='bots_socials_preview'){
       const files=f.ambiguous?[{file:'Ownerchar_old.ini',revision:'file-'+f.revision},{file:'Ownerchar_current.ini',revision:'file-'+f.revision}]:[{file:'Ownerchar_'+f.profile+'.ini',revision:'file-'+f.revision}];
       const supported=!f.ambiguous||!!a.character_file;value={supported,reason:supported?'Review commands and free slots.':'Several matching character files. Choose the actual file, then preview again.',identity:identity(),character_files:files,character_file:a.character_file||(supported?files[0].file:null),file_revision:'file-'+f.revision,preview_token:supported?'buttons-'+f.revision:null,socials:supported?commandSocials(a,owner):[],empty_hotbar_slots:[{bar:1,page:1,button:1},{bar:1,page:1,button:2}],backups:f.backups};
      }
      if(op==='bots_socials_install'){
       if(f.failInstall){f.failInstall=false;error='Character file changed. Preview again.';}
       else{if(a.file_revision!=='file-'+f.revision)throw Error('Stale file revision');f.revision++;f.backups=[{id:'backup-1',file:a.character_file,created_at:'2026-10-10 06:00'}];value={message:'Companion buttons saved for the next launch.',backup:'backup-1'};}
      }
      if(op==='bots_socials_restore'){if(a.backup_id!=='backup-1')throw Error('Missing backup');f.revision++;value={message:'Previous character buttons restored.'};}
     }
     result={id:String(f.jobs.length+1),operation:op,status:error?'error':'done',result:value,error};f.jobs.push(result);
    }
    window.nativeReply(id,{ok:true,result});
   }catch(error){window.nativeReply(id,{ok:false,error:error.message});}},5);}};
  },botCommandCatalogue);
  await page.goto(`http://127.0.0.1:${server.address().port}/`);
  await page.waitForFunction(()=>lastState?.profile==='custom'&&lastClientNative&&!polling);
  await page.locator('nav [data-tab=bots]').click();await page.waitForFunction(()=>botsUi.status&&!botsUi.working);
  assert(await page.locator('#bots').isVisible());assert.equal(await page.locator('nav button').count(),11);
  await page.fill('#bots-character-search','Touchscreen');await page.click('#bots-search');await page.waitForFunction(()=>!botsUi.working);
  assert.equal(await page.locator('#bots-character option').count(),2,'Account search narrows active characters');
  await page.selectOption('#bots-character','42');await page.waitForFunction(()=>botsUi.owner?.id===42&&!botsUi.working);
  assert((await page.textContent('#bots-owner')).includes('Level 35'));assert(await page.isDisabled('#bots-add-draft'));assert(await page.locator('#bots-build-link').isVisible());
  await page.click('#bots-build-link');assert(await page.locator('#build').isVisible());await page.locator('nav [data-tab=bots]').click();
  await page.evaluate(()=>fixture.storageNeeded=true);await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&botsUi.status.storage.needed);assert(await page.locator('#bots-storage-panel').isVisible());assert.equal(await page.evaluate(()=>fixture.calls.filter(c=>c.op==='bots_storage_enable').length),0,'Storage conversion never starts automatically');
  await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.client=true;await poll();});assert(await page.isDisabled('#bots-review-storage'));await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.client=false;await poll();});await page.click('#bots-review-storage');await page.waitForFunction(()=>botsUi.storagePreview&&!botsUi.working);assert((await page.textContent('#bots-storage-changes')).includes('character_data'));assert((await page.textContent('#bots-storage-changes')).includes('MyISAM'));assert((await page.textContent('#bots-storage-changes')).includes('InnoDB'));await page.setViewportSize({width:393,height:852});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Storage review fits portrait viewport');fs.mkdirSync('ui-reports',{recursive:true});await page.screenshot({path:'ui-reports/bots-storage-393.png',fullPage:true});await page.setViewportSize({width:1280,height:720});const storageIdentity=await page.evaluate(()=>botsUi.status.identity);await page.evaluate(()=>fixture.failStorage=true);await page.click('#bots-enable-storage');await page.waitForFunction(()=>!botsUi.working&&botsUi.storageResult?.complete===false);assert.notEqual(await page.evaluate(()=>botsUi.status.identity),storageIdentity,'Partial storage changes refresh deployment identity');assert((await page.textContent('#bots-storage-result')).includes('backups/storage-2.sql.gz'));assert((await page.textContent('#bots-storage-result')).includes('Still to enable: bot_data'));assert(await page.locator('#bots-storage-preview').isHidden());assert(await page.isDisabled('#bots-enable-storage'));assert.equal(await page.inputValue('#bots-character'),'','Storage identity changes clear the owner selection');
  await page.click('#bots-review-storage');await page.waitForFunction(()=>botsUi.storagePreview&&!botsUi.working);assert(!(await page.textContent('#bots-storage-changes')).includes('character_data'),'New review lists only remaining tables');await page.click('#bots-enable-storage');await page.waitForFunction(()=>!botsUi.working&&botsUi.storageResult?.complete===true);assert((await page.textContent('#bots-storage-result')).includes('backups/storage-3.sql.gz'));assert(await page.locator('#bots-export-storage-backup').isVisible());const enable=await page.evaluate(()=>fixture.calls.filter(c=>c.op==='bots_storage_enable'));assert.equal(enable.length,2);assert.notEqual(enable[0].a.preview_hash,enable[1].a.preview_hash);await page.selectOption('#bots-character','42');await page.waitForFunction(()=>!botsUi.working&&botsUi.owner?.id===42);
  await page.evaluate(()=>{fixture.creation=true;localStorage.creation='true';});await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&botsUi.owner.creation.available);
  await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.running=true;await poll();});await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&!botsUi.owner.creation.available);await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.running=false;await poll();});assert((await page.textContent('#bots-create-status')).includes('Refresh roster'),'Readiness snapshot explains refreshing after stopping');assert(await page.isDisabled('#bots-add-draft'));await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&botsUi.owner.creation.available);
  await page.click('#bots-add-draft');await page.waitForFunction(()=>!botsUi.working);
  await page.fill('#bots-draft-0-name','Alpha');await page.selectOption('#bots-draft-0-race','1');await page.selectOption('#bots-draft-0-class','1');await page.selectOption('#bots-draft-0-gender','0');
  assert(!(await page.isDisabled('#bots-preview-create')));
  await page.selectOption('#bots-draft-0-race','128');assert.equal(await page.inputValue('#bots-draft-0-class'),'','Race change clears an invalid class');assert.equal(await page.locator('#bots-draft-0-class option[value="1"]').count(),0);assert(await page.isDisabled('#bots-preview-create'));
  await page.selectOption('#bots-draft-0-class','11');await page.click('#bots-add-draft');await page.waitForFunction(()=>!botsUi.working);
  await page.fill('#bots-draft-1-name','Betabot');await page.selectOption('#bots-draft-1-race','1');await page.selectOption('#bots-draft-1-class','13');await page.selectOption('#bots-draft-1-gender','1');
  await page.fill('#bots-draft-1-name','alpha');assert(await page.isDisabled('#bots-preview-create'),'Draft names are unique without case sensitivity');await page.fill('#bots-draft-1-name','Betabot');
  await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.running=true;await poll();});assert(await page.isDisabled('#bots-preview-create'));assert(await page.isDisabled('#bots-add-draft'));assert(!(await page.isDisabled('#bots-character-search')),'Stopped guard applies to writes, not browsing');
  await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.running=false;fixture.client=true;await poll();});assert(await page.isDisabled('#bots-preview-create'));
  await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.client=false;fixture.jobs.push({id:'busy',status:'running',operation:'build'});await poll();});assert(await page.isDisabled('#bots-preview-create'));
  await page.evaluate(async()=>{while(polling)await new Promise(resolve=>setTimeout(resolve,10));fixture.jobs=[];await poll();});await page.waitForFunction(()=>!document.getElementById('bots-preview-create').disabled);
  await page.click('#bots-preview-create');await page.waitForFunction(()=>botsUi.preview&&!botsUi.working);assert(await page.locator('#bots-create-preview').isVisible());assert((await page.textContent('#bots-create-review')).includes('Necromancer'));
  const firstReview=await page.evaluate(()=>botsUi.preview.request_id);await page.click('#bots-preview-create');await page.waitForFunction(()=>botsUi.preview&&!botsUi.working);assert.notEqual(await page.evaluate(()=>botsUi.preview.request_id),firstReview,'A new review uses a fresh creation token');
  await page.evaluate(()=>fixture.failGenerate=true);await page.click('#bots-generate');await page.waitForFunction(()=>!botsUi.working&&botsUi.result.includes('did not commit'));
  assert.equal(await page.evaluate(()=>fixture.rosters[42].length),1,'Failed generation leaves existing roster intact');
  await page.click('#bots-generate');await page.waitForFunction(()=>!botsUi.working&&botsUi.roster.length===3);
  const generate=await page.evaluate(()=>fixture.calls.filter(c=>c.op==='bots_generate'));assert.equal(generate.length,2);assert.equal(generate[0].a.request_id,generate[1].a.request_id,'Retry reuses the request ID');assert.equal(generate[0].a.preview_hash,generate[1].a.preview_hash);assert.equal(generate[1].a.owner_id,42);assert.equal(generate[1].a.__profile,'custom');
  assert.equal(await page.locator('#bots-drafts .bots-draft').count(),0);assert.equal(await page.locator('#bots-roster input:checked').count(),2,'New companions selected after creation');
  await page.click('#bots-preview-socials');await page.waitForFunction(()=>botsUi.socials?.supported&&!botsUi.working);
  assert((await page.textContent('#bots-socials-list')).includes('/invite'));assert.equal(await page.inputValue('#bots-placement-spawn_group-000000000000000000000101'),'','Hotbar placements require an explicit choice');
  await page.selectOption('#bots-placement-spawn_group-000000000000000000000101','1:1:1');await page.selectOption('#bots-placement-spawn_group-000000000000000000000102','1:1:1');assert(await page.isDisabled('#bots-install-socials'),'Duplicate hotbar slots blocked');await page.selectOption('#bots-placement-spawn_group-000000000000000000000102','1:1:2');
  await page.evaluate(()=>fixture.failInstall=true);await page.click('#bots-install-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.result.includes('Buttons pending'));
  assert.equal(await page.evaluate(()=>fixture.rosters[42].length),3,'File failure preserves generated companions');assert.equal(await page.evaluate(()=>fixture.calls.filter(c=>c.op==='bots_generate').length),2,'Social retry never creates more bots');
  await page.click('#bots-preview-socials');await page.waitForFunction(()=>botsUi.socials?.supported&&!botsUi.working);await page.selectOption('#bots-placement-spawn_group-000000000000000000000101','1:1:1');await page.selectOption('#bots-placement-spawn_group-000000000000000000000102','1:1:2');await page.click('#bots-install-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.result.includes('saved for the next'));
  const install=await page.evaluate(()=>fixture.calls.filter(c=>c.op==='bots_socials_install').at(-1).a);assert.deepEqual(install.placements,[{social_id:'spawn_group.'+String(101).padStart(24,'0'),bar:1,page:1,button:1},{social_id:'spawn_group.'+String(102).padStart(24,'0'),bar:1,page:1,button:2}]);assert.equal(install.character_file,'Ownerchar_custom.ini');assert.equal(install.file_revision,'file-1');assert(install.preview_token);
  await page.click('#bots-backups-panel > summary');await page.selectOption('#bots-backup','backup-1');await page.click('#bots-restore-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.result.includes('restored'));
  const restore=await page.evaluate(()=>fixture.calls.find(c=>c.op==='bots_socials_restore').a);assert.equal(restore.owner_id,42);assert.equal(restore.file_revision,'file-2');
  await page.evaluate(()=>fixture.ambiguous=true);await page.click('#bots-preview-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.socials?.character_files.length===2);await page.selectOption('#bots-character-file','');await page.click('#bots-preview-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.socials?.supported===false);assert(await page.locator('#bots-socials-preview').isHidden());
  await page.selectOption('#bots-character-file','Ownerchar_current.ini');await page.click('#bots-preview-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.socials?.supported);assert((await page.textContent('#bots-socials-file')).includes('Ownerchar_current.ini'));
  // Changing owner clears previews, saved selection and draft receipts.
  await page.fill('#bots-character-search','');await page.click('#bots-search');await page.waitForFunction(()=>!botsUi.working);await page.selectOption('#bots-character','43');await page.waitForFunction(()=>!botsUi.working&&botsUi.owner.id===43);assert.equal(await page.locator('#bots-roster input:checked').count(),0);assert(await page.locator('#bots-socials-preview').isHidden());
  await page.click('#bots-add-draft');await page.waitForFunction(()=>!botsUi.working);await page.fill('#bots-draft-0-name','Unsaved');
  // A creation roster may exceed one party; all six names can be selected for chunked command export.
  for(let index=0;index<6;index++){if(index){await page.click('#bots-add-draft');await page.waitForFunction(()=>!botsUi.working);}await page.fill(`#bots-draft-${index}-name`,['Alphateam','Betateam','Gammateam','Deltateam','Epsilonteam','Zetateam'][index]);await page.selectOption(`#bots-draft-${index}-race`,'1');await page.selectOption(`#bots-draft-${index}-class`,'1');await page.selectOption(`#bots-draft-${index}-gender`,'0');}await page.click('#bots-preview-create');await page.waitForFunction(()=>botsUi.preview&&!botsUi.working);await page.click('#bots-generate');await page.waitForFunction(()=>!botsUi.working&&botsUi.roster.length===6);assert.equal(await page.locator('#bots-roster input:checked').count(),6,'Batch creation keeps all names for command export');assert(!(await page.isDisabled('#bots-roster input[data-bot-id="105"]')),'Sixth saved bot remains selected for command export');await page.click('#bots-add-draft');await page.waitForFunction(()=>!botsUi.working);await page.fill('#bots-draft-0-name','Unsaved');
  // Full profile switch reload discards the draft and never carries another world's identity.
  for(const profile of ['traditional','takp']){
   await page.click('#runtime-close');await page.waitForFunction(()=>!lastNative.alive&&!polling&&!busy);await page.selectOption('#world-profile',profile);await page.click('#switch-profile');await page.waitForFunction(p=>activeProfile===p&&document.body.dataset.profile===p&&!polling&&!busy,profile);await page.click('#runtime-open');await page.waitForFunction(()=>lastNative.alive&&lastState&&!polling&&!busy);await page.locator('nav [data-tab=bots]').click();await page.waitForFunction(()=>botsUi.status&&!botsUi.working);assert.equal(await page.locator('#bots-drafts .bots-draft').count(),0,'World switch clears drafts');if(profile==='takp')assert(await page.locator('#bots-storage-panel').isHidden(),'TAKP never offers modern storage migration');assert.equal(await page.inputValue('#bots-character'),'');await page.selectOption('#bots-character','42');await page.waitForFunction(()=>botsUi.owner?.id===42&&!botsUi.working);await page.check('#bots-roster input[data-bot-id="8"]');await page.click('#bots-preview-socials');await page.waitForFunction(()=>botsUi.socials?.supported&&!botsUi.working);const request=await page.evaluate(()=>fixture.calls.filter(c=>c.op==='bots_socials_preview').at(-1).a);assert.equal(request.identity,profile+'-deployment-v1');assert.equal(request.__profile,profile);const commands=await page.textContent('#bots-socials-list');assert(commands.includes(profile==='takp'?'/say #bot spawn Savedbot':'/say ^botspawn Savedbot'));if(profile==='takp')assert(!commands.includes('/invite'),'TAKP auto-groups on spawn');
   if(profile==='takp'){
    assert(await page.locator('#bots-command-panel').isVisible());assert(await page.isChecked('#bots-command-spawn'));assert(!(await page.isChecked('#bots-command-revive')),'Only Spawn defaults on');
    await page.uncheck('#bots-command-spawn');assert(await page.isDisabled('#bots-preview-socials'),'Choose at least one command');assert(await page.locator('#bots-socials-preview').isHidden(),'Command edit invalidates preview');
    await page.check('#bots-command-spawn');await page.check('#bots-command-revive');
    await page.evaluate(()=>{fixture.rosters[42].push({id:9,name:'Secondbot',race:1,class:1,gender:0});});await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&botsUi.roster.length===2);await page.check('#bots-roster input[data-bot-id="9"]');await page.click('#bots-preview-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.socials?.socials?.length===2);
    const party=await page.evaluate(()=>botsUi.socials.socials);assert.deepEqual(party[0].lines,['/say #bot spawn Savedbot','/say #bot spawn Secondbot']);assert.deepEqual(party[1].lines,['/say #bot revive Savedbot','/say #bot revive Secondbot']);assert.notEqual(party[0].social_id,party[1].social_id);
    for(const viewport of [{width:1280,height:720},{width:393,height:852}]){await page.setViewportSize(viewport);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'TAKP command picker and combined socials fit viewport');fs.mkdirSync('ui-reports',{recursive:true});await page.screenshot({path:`ui-reports/bots-commands-${viewport.width}.png`,fullPage:true});}await page.setViewportSize({width:1280,height:720});
    const places=page.locator('#bots-socials-list select');await places.nth(0).selectOption('1:1:1');await places.nth(1).selectOption('1:1:1');assert(await page.isDisabled('#bots-install-socials'));await places.nth(1).selectOption('1:1:2');await page.click('#bots-install-socials');await page.waitForFunction(()=>!botsUi.working);
    const written=await page.evaluate(()=>fixture.calls.filter(c=>c.op==='bots_socials_install').at(-1).a);assert.deepEqual(written.actions,['spawn','revive']);assert.deepEqual(written.placements,[{social_id:party[0].social_id,bar:1,page:1,button:1},{social_id:party[1].social_id,bar:1,page:1,button:2}]);
    await page.check('#bots-command-follow');assert(await page.locator('#bots-socials-preview').isHidden());assert.deepEqual(await page.evaluate(()=>botsUi.placements),{});await page.uncheck('#bots-command-follow');
    await page.evaluate(()=>{for(let i=10;i<=13;i++)fixture.rosters[42].push({id:i,name:'Named'+String.fromCharCode(65+i),race:1,class:1,gender:0});});await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&botsUi.roster.length===6);for(const id of [10,11,12,13])await page.check('#bots-roster input[data-bot-id="'+id+'"]');assert.equal(await page.locator('#bots-roster input:checked').count(),6,'TAKP allows more than five selected names');await page.click('#bots-preview-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.socials?.socials?.length===4);const chunks=await page.evaluate(()=>botsUi.socials.socials);assert.deepEqual(chunks.map(c=>c.lines.length),[5,1,5,1]);assert.deepEqual(chunks.map(c=>c.label),['Spawn party 1','Spawn party 2','Revive party 1','Revive party 2']);
    await page.uncheck('#bots-command-revive');await page.evaluate(()=>{fixture.rosters[42]=fixture.rosters[42].slice(0,1);});await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&botsUi.roster.length===1);
   }else{
    assert(await page.locator('#bots-command-panel').isVisible(),'Modern worlds expose their own command catalogue');assert(await page.isChecked('#bots-command-spawn_group'));assert(!(await page.isChecked('#bots-command-spawn')),'Combined spawn does not replace guarded invites by default');assert.equal(await page.locator('#bots-command-revive').count(),0,'Modern servers do not expose TAKP revive');
    await page.check('#bots-command-follow');await page.locator('#bots-command-list details').filter({has:page.locator('#bots-command-report')}).locator('summary').click();await page.check('#bots-command-report');await page.click('#bots-preview-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.socials.socials.length===3);const modern=await page.evaluate(()=>botsUi.socials.socials);assert.deepEqual(modern[0].lines,['/pause 20, /say ^botspawn Savedbot','/target Ownerchar','/pause 5, /target Savedbot','/invite']);assert.deepEqual(modern[1].lines,['/say ^follow reset byname Savedbot']);assert.deepEqual(modern[2].lines,['/say ^botreport byname Savedbot']);
    for(const viewport of [{width:1280,height:720},{width:393,height:852}]){await page.setViewportSize(viewport);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Modern command picker fits viewport');fs.mkdirSync('ui-reports',{recursive:true});await page.screenshot({path:`ui-reports/bots-modern-${viewport.width}.png`,fullPage:true});}await page.setViewportSize({width:1280,height:720});
    await page.uncheck('#bots-command-spawn_group');assert(await page.locator('#bots-socials-preview').isHidden());await page.uncheck('#bots-command-follow');await page.uncheck('#bots-command-report');assert(await page.isDisabled('#bots-preview-socials'));await page.check('#bots-command-spawn');await page.click('#bots-preview-socials');await page.waitForFunction(()=>!botsUi.working&&botsUi.socials.socials.length===1);assert.deepEqual(await page.evaluate(()=>botsUi.socials.socials[0].lines),['/say ^botspawn Savedbot']);assert(!(await page.textContent('#bots-socials-list')).includes('/invite'));
   }

  }
  // Deployment changes cannot replay a stale generation preview into the new world.
  await page.click('#bots-add-draft');await page.waitForFunction(()=>!botsUi.working);await page.fill('#bots-draft-0-name','Staledraft');await page.selectOption('#bots-draft-0-race','1');await page.selectOption('#bots-draft-0-class','1');await page.selectOption('#bots-draft-0-gender','0');await page.click('#bots-preview-create');await page.waitForFunction(()=>botsUi.preview&&!botsUi.working);await page.evaluate(()=>fixture.identityVersion=2);await page.click('#bots-generate');await page.waitForFunction(()=>!botsUi.working&&botsUi.result.includes('Stale identity'));assert.equal(await page.evaluate(()=>fixture.rosters[42].length),1);await page.click('#bots-refresh');await page.waitForFunction(()=>!botsUi.working&&botsUi.status.identity.endsWith('v2'));assert.equal(await page.inputValue('#bots-character'),'');assert.equal(await page.locator('#bots-drafts .bots-draft').count(),0);assert(await page.locator('#bots-create-preview').isHidden());
  await page.selectOption('#bots-character','42');await page.waitForFunction(()=>!botsUi.working&&botsUi.owner?.id===42);await page.click('#bots-add-draft');await page.waitForFunction(()=>!botsUi.working);await page.check('#bots-roster input[data-bot-id="8"]');await page.click('#bots-preview-socials');await page.waitForFunction(()=>botsUi.socials?.supported&&!botsUi.working);fs.mkdirSync('ui-reports',{recursive:true});
  for(const viewport of [{width:1280,height:720},{width:393,height:852}]){await page.setViewportSize(viewport);await page.evaluate(()=>scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Bots editor fits viewport');for(const theme of ['necromancer','monk']){await page.selectOption('#launcher-theme',theme);const art=await page.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--scene-image'));assert(art.includes(theme==='monk'?'meditation':'grimoire'));}await page.screenshot({path:`ui-reports/bots-${viewport.width}.png`,fullPage:true});}
  assert.deepEqual(errors,[]);console.log('PASS: all-world Bots tab, searchable character ownership, valid combinations, preview/generate retry, stopped/busy guards, social/hotbar preview, preserved roster on file failure, backup restore, profile isolation and touch layout');
 }catch(error){if(page){fs.mkdirSync('ui-reports',{recursive:true});try{const diagnostic=await page.evaluate(()=>({profile:activeProfile,tab:currentTab,busy,polling,native:lastNative,client:lastClientNative,state:lastState,bots:{generation:botsUi.generation,status:botsUi.status,owner:botsUi.owner,working:botsUi.working,result:botsUi.result,preview:botsUi.preview,selected:[...botsUi.selected],drafts:botsUi.drafts},calls:fixture.calls.slice(-20)}));fs.writeFileSync('ui-reports/bots-failure-state.json',JSON.stringify(diagnostic,null,2));await page.screenshot({path:'ui-reports/bots-failure.png',fullPage:true,timeout:7000});}catch{}}throw error;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
